using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Yogurt.Generator
{
    [Generator]
    public sealed class AspectCacheGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor unsupportedAspect = new(
            "YOGURT001", "Cannot generate aspect mask",
            "Cannot generate the component mask for '{0}': {1}",
            "Yogurt", DiagnosticSeverity.Error, isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<INamedTypeSymbol?> aspects = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is TypeDeclarationSyntax,
                    static (ctx, _) => GetAspect(ctx))
                .Where(static type => type != null);

            context.RegisterSourceOutput(aspects.Collect(), static (ctx, types) => Emit(ctx, types));
        }

        private static INamedTypeSymbol? GetAspect(GeneratorSyntaxContext context)
        {
            INamedTypeSymbol? type = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;
            return type is { TypeKind: TypeKind.Struct } && Implements(type, "Yogurt.IAspect") ? type : null;
        }

        private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> types)
        {
            StringBuilder registrations = new();
            foreach (INamedTypeSymbol aspect in types.Where(t => t != null).Select(t => t!)
                         .GroupBy(Display).Select(g => g.First()).OrderBy(Display))
            {
                HashSet<ITypeSymbol> components = new(SymbolEqualityComparer.Default);
                HashSet<ITypeSymbol> visiting = new(SymbolEqualityComparer.Default);
                string? error = !IsEmittable(aspect)
                    ? "the aspect must be accessible and must not contain type parameters"
                    : CollectComponents(aspect, components, visiting);

                if (error != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(unsupportedAspect,
                        aspect.Locations.FirstOrDefault(), Display(aspect), error));
                    continue;
                }

                registrations.Append("            global::Yogurt.AspectCache.Register<")
                    .Append(Display(aspect)).Append(">(new global::Yogurt.QueryOfEntity()");
                foreach (ITypeSymbol component in components.OrderBy(Display))
                    registrations.Append(".With<").Append(Display(component)).Append(">()");
                registrations.AppendLine(");");
            }

            if (registrations.Length == 0)
                return;

            StringBuilder source = new();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("namespace Yogurt");
            source.AppendLine("{");
            source.AppendLine("    internal static class AspectCache_Roslyn");
            source.AppendLine("    {");
            source.AppendLine("        private static bool registered;");
            RuntimeInitialization.AppendAttribute(source);
            source.AppendLine("        internal static void Register()");
            source.AppendLine("        {");
            source.AppendLine("            if (registered) return;");
            source.Append(registrations);
            source.AppendLine("            registered = true;");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            context.AddSource("gen.AspectCache_Roslyn.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }

        private static string? CollectComponents(INamedTypeSymbol aspect,
            HashSet<ITypeSymbol> components, HashSet<ITypeSymbol> visiting)
        {
            if (!visiting.Add(aspect))
                return $"nested aspect '{Display(aspect)}' creates a cycle";

            for (INamedTypeSymbol? current = aspect; current != null; current = current.BaseType)
            {
                foreach (IPropertySymbol property in current.GetMembers().OfType<IPropertySymbol>())
                {
                    if (property.DeclaredAccessibility != Accessibility.Public)
                        continue;

                    // Roslyn exposes the component type directly for ref and ref readonly properties.
                    ITypeSymbol type = property.Type;
                    if (Implements(type, "Yogurt.IComponent"))
                    {
                        if (!IsEmittable(type))
                            return $"component '{Display(type)}' is not accessible or contains type parameters";
                        components.Add(type);
                    }

                    if (type is INamedTypeSymbol nested && Implements(type, "Yogurt.IAspect"))
                    {
                        string? error = CollectComponents(nested, components, visiting);
                        if (error != null)
                            return error;
                    }
                }
            }

            visiting.Remove(aspect);
            return null;
        }

        private static bool Implements(ITypeSymbol type, string interfaceName)
            => type.AllInterfaces.Any(i => i.ToDisplayString() == interfaceName);

        private static bool IsEmittable(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named || named.IsUnboundGenericType)
                return false;

            for (INamedTypeSymbol? current = named; current != null; current = current.ContainingType)
            {
                if (current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)
                    || current.TypeArguments.Any(argument => !IsEmittable(argument)))
                    return false;
            }

            return true;
        }

        private static string Display(ITypeSymbol type)
            => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }
}
