using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Yogurt.Generator
{
    [Generator]
    public sealed class ComponentRegistryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<INamedTypeSymbol?> components = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is TypeDeclarationSyntax,
                    static (generatorContext, _) => GetComponent(generatorContext))
                .Where(static type => type != null);

            IncrementalValueProvider<ImmutableArray<INamedTypeSymbol?>> componentTypes = components.Collect();
            context.RegisterSourceOutput(componentTypes, static (productionContext, types) => Emit(productionContext, types));
        }

        private static INamedTypeSymbol? GetComponent(GeneratorSyntaxContext context)
        {
            INamedTypeSymbol? type = context.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)context.Node) as INamedTypeSymbol;
            if (type == null || type.IsAbstract || !IsEmittable(type))
            {
                return null;
            }

            return type.AllInterfaces.Any(interfaceType => interfaceType.ToDisplayString() == "Yogurt.IComponent")
                ? type
                : null;
        }

        private static bool IsEmittable(INamedTypeSymbol type)
        {
            for (INamedTypeSymbol? current = type; current != null; current = current.ContainingType)
            {
                bool inaccessible = current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal);
                if (inaccessible || current.IsGenericType)
                {
                    return false;
                }
            }

            return true;
        }

        private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> types)
        {
            string[] components = types
                .Where(static type => type != null)
                .Select(static type => type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Distinct()
                .OrderBy(static type => type)
                .ToArray();

            if (components.Length == 0)
            {
                return;
            }

            StringBuilder source = new();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("namespace Yogurt");
            source.AppendLine("{");
            source.AppendLine("    internal static class ComponentRegistry_Roslyn");
            source.AppendLine("    {");
            source.AppendLine("        private static bool registered;");
            source.AppendLine();
            source.AppendLine("#if UNITY_2019_1_OR_NEWER");
            source.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            source.AppendLine("#endif");
            source.AppendLine("        internal static void Register()");
            source.AppendLine("        {");
            source.AppendLine("            if (registered)");
            source.AppendLine("            {");
            source.AppendLine("                return;");
            source.AppendLine("            }");
            source.AppendLine();

            foreach (string component in components)
            {
                source.Append("            global::Yogurt.StorageFactory.Create<");
                source.Append(component);
                source.AppendLine(">();");
            }

            source.AppendLine();
            source.AppendLine("            registered = true;");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource("gen.ComponentRegistry_Roslyn.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }
    }
}
