using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AspectSourceGenerator
{
    /// <summary>
    /// Finds all statically resolvable query chains:
    ///     Query.Of&lt;T&gt;() / Query.Single&lt;T&gt;() [.With&lt;T&gt;()* / .Without&lt;T&gt;()*]
    /// and emits a per-assembly warmup registration so all Groups are created
    /// at world startup (empty world) instead of lazily mid-runtime.
    ///
    /// Limitations (by design, best-effort):
    /// - Only literal fluent chains rooted at Query.Of / Query.Single are detected.
    ///   Chains built through variables/conditionals are skipped.
    /// - Chains containing open generic type arguments are skipped entirely
    ///   (warming a prefix would create a Group nobody queries).
    /// </summary>
    [Generator]
    public class QueryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<string?> chains = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => IsQueryRootCandidate(node),
                    transform: static (ctx, _) => TryBuildChain(ctx))
                .Where(static chain => chain != null);

            IncrementalValueProvider<ImmutableArray<string?>> collected = chains.Collect();

            context.RegisterSourceOutput(collected, static (ctx, allChains) =>
            {
                if (allChains.IsDefaultOrEmpty)
                    return;

                string[] unique = allChains
                    .Where(c => c != null)
                    .Select(c => c!)
                    .Distinct()
                    .OrderBy(c => c)
                    .ToArray();

                if (unique.Length == 0)
                    return;

                StringBuilder sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("namespace Yogurt");
                sb.AppendLine("{");
                sb.AppendLine("    internal static class QueryWarmup_Roslyn");
                sb.AppendLine("    {");
                sb.AppendLine("        private static bool registered;");
                sb.AppendLine();
                sb.AppendLine("#if UNITY_2019_1_OR_NEWER");
                sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
                sb.AppendLine("#endif");
                sb.AppendLine("        internal static void Register()");
                sb.AppendLine("        {");
                sb.AppendLine("            // Guard for disabled domain reload: statics survive, list must not grow.");
                sb.AppendLine("            if (registered)");
                sb.AppendLine("                return;");
                sb.AppendLine("            registered = true;");
                sb.AppendLine();
                sb.AppendLine("            QueryWarmup.Register(() =>");
                sb.AppendLine("            {");
                foreach (string chain in unique)
                {
                    sb.AppendLine($"                {chain}.Warmup();");
                }
                sb.AppendLine("            });");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                ctx.AddSource("gen.QueryWarmup_Roslyn.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        private static bool IsQueryRootCandidate(SyntaxNode node)
        {
            return node is InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax
                {
                    Name: GenericNameSyntax { Identifier.Text: "Of" or "Single" }
                }
            };
        }

        private static string? TryBuildChain(GeneratorSyntaxContext ctx)
        {
            InvocationExpressionSyntax rootInvocation = (InvocationExpressionSyntax)ctx.Node;

            if (ctx.SemanticModel.GetSymbolInfo(rootInvocation).Symbol is not IMethodSymbol rootMethod)
                return null;

            if (rootMethod.ContainingType?.ToDisplayString() != "Yogurt.Query")
                return null;

            if (rootMethod.TypeArguments.Length != 1)
                return null;

            ITypeSymbol rootType = rootMethod.TypeArguments[0];
            if (!IsEmittable(rootType))
                return null;

            StringBuilder chain = new StringBuilder();
            chain.Append("global::Yogurt.Query.Of<").Append(Display(rootType)).Append(">()");

            // Walk outward through the fluent chain: .With<T>() / .Without<T>()
            SyntaxNode current = rootInvocation;
            while (current.Parent is MemberAccessExpressionSyntax member
                   && member.Parent is InvocationExpressionSyntax outer
                   && member.Name.Identifier.Text is "With" or "Without")
            {
                if (ctx.SemanticModel.GetSymbolInfo(outer).Symbol is not IMethodSymbol chainMethod
                    || chainMethod.TypeArguments.Length != 1)
                    return null;

                string containing = chainMethod.ContainingType?.OriginalDefinition.ToDisplayString() ?? string.Empty;
                if (containing != "Yogurt.QueryOfEntity" && containing != "Yogurt.QueryOfAspect<TAspect>")
                    break; // some unrelated With/Without — the chain so far is the real composition

                ITypeSymbol argType = chainMethod.TypeArguments[0];
                if (!IsEmittable(argType))
                    return null; // open generic inside the chain — skip whole chain, a prefix Group would be dead weight

                chain.Append('.').Append(member.Name.Identifier.Text)
                     .Append('<').Append(Display(argType)).Append(">()");

                current = outer;
            }

            return chain.ToString();
        }

        /// Type must be closed (no type parameters) and visible to generated code
        /// at namespace scope within the same assembly (public/internal all the way up).
        private static bool IsEmittable(ITypeSymbol type)
        {
            if (type is IErrorTypeSymbol or ITypeParameterSymbol)
                return false;

            for (INamedTypeSymbol? container = type.ContainingType; container != null; container = container.ContainingType)
            {
                if (container.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                    return false;
            }

            if (type.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal or Accessibility.NotApplicable))
                return false;

            if (type is INamedTypeSymbol { IsGenericType: true } named)
                return named.TypeArguments.All(IsEmittable);

            return true;
        }

        private static string Display(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
    }
}
